/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bank;

/**
 *
 * @author Sheila indri
 */
public class bank extends javax.swing.JFrame {

    /** Creates new form bank */
    public bank() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bahasa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELAMAT DATANG");

        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");

        jLabel3.setText("BRI SYARIAH MALANG");

        Bahasa.setText("Pilih Bahasa");
        Bahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Bahasa)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addComponent(Bahasa)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahasaActionPerformed

        public Bahasa(){
} 
        void tampilMenuBahasa(){
        Bahasa idn = new Bahasa();
        idn.setNamaBahasa("Indonesia");
        Bahasa eng = new Bahasa();
        eng.setNamaBahasa("English");
        
        System.out.println("Pilih Bahasa/Select Languange:");
        System.out.println("=============================");
        System.out.println("1. " + idn.getNamaBahasa() );
        System.out.println("2. " + eng.getNamaBahasa() );
        System.out.println("=============================");
    }
    
    void tampilInputPin(){
        if(Nasabah.noBahasaPilihan == 1){
            tampilInputPinIN();
        }else if(Nasabah.noNasabahPilihan == 2){
            tampilInputPinEN();
        }
    }
    
    void tampilInputPinIN(){
        System.out.println("Masukkan Pin Anda: ");
    }
    
  void tampilInputPinEN(){
      System.out.println("Insert Your Password: ");
  }
  
  void tampilMenu(){
      if(Nasabah.noBahasaPilihan == 1){
          tampilMenuIN();
      }else if(Nasabah.noBahasaPilihan == 2){
          tampilMenuEN();
      }
    }
  
  void tampilMenuIN(){
      Menu INcekSaldo = new Menu();
      INcekSaldo.setNamaMenu("Cek Saldo");
      Menu INtransfer = new Menu();
      INtransfer.setNamaMenu("Transfer");
      Menu INtarikTunai = new Menu();
      INtarikTunai.setNamaMenu("Tarik Tunai");
      Menu INgantiPin = new Menu();
      INgantiPin.setNamaMenu("Ganti Pin");
      
      System.out.println("Pilih Menu Transaksi");
      System.out.println("=====================");
      
  }

        // TODO add your handling code here:
    }//GEN-LAST:event_BahasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bank().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bahasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
